---
title: "lesson3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
rm(list = ls())
x<-1:10
y<-c(1L,2L,3L,4L,5L,6L,7L,8L,9L,10L)
x[1:5]
x[-2:4]
x[-(2:4)]
str(x)
names(x)<- c("a","b")
x["b"]
x["b"]+3
x[c(T,T,F)]
x<4
x[x<4]

```
```{r}
x <- c(5.4, 6.2, 7.1, 4.8, 7.5, 6.2)
names(x) <- c('a', 'b', 'c', 'd', 'e', 'f')
x[-(2:4)]
x[-2:4]
-x[2:4]
x[names(x) == "a"]
x[which(names(x) == "a")]

lst <- list(1:3, "a", c(TRUE, FALSE, TRUE), c(2.3, 5.9))
names(lst) <- c("A","B","C","D")
lst[1]
lst[[3]]
lst[3]
str(lst[[3]])
str(lst[3])
str(lst[["D"]])
str(lst["D"])
```
```{r}
lst <- list(1:3, "a", c(TRUE, FALSE, TRUE), c(2.3, 5.9))
names(lst) <- c("A","B","C","D")
# command 1:
lst[1][2]
# command 2:
lst[[1]][2]
lst[1:2][2]
```
command 1: first list, only 1 element, the second element is non.
command 2: first list as vector, 3 element.
command 3: first 2 list, 2 element.

```{r}
df <- data.frame(
  x = 1:3,
  y = c("a", "b", "c"),
  z = c(TRUE,FALSE,TRUE),
  stringsAsFactors = FALSE)
str(df)
df
str(df[,2])
df[,2]
df[2]
str(df[2])
df[[2]]
str(df[[2]])

df[3,2]
str(df[3,2])
df[[2]][3]
str(df[[2]][3])
```

```{r}
if (!require("tidyverse")) install.packages("tidyverse")
library(tidyverse)
read_csv("a,b,c
         1,2,3
         4,5,6")
df<-read_csv("a,b,c
         1,2,3
         4,5,6")
View(df)
df[1]

```






